server:
  port: 9090
  servlet:
    context-path: /library-api

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/library_db?useSSL=false
    username: lucasbarbosa
    password: lucas123
    driverClassName: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

feign:
  client:
    stock:
      name: Stock
      url: https://www.randomnumberapi.com/api/v1.0
    agify:
      name: Agify
      url: https://api.agify.io/
    country:
      name: Country
      url: https://restcountries.eu/rest/v2/alpha

seller:
  token:
    validity: 60
