server:
  port: 9090
  servlet:
    context-path: /library-api

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/library_db?useSSL=false
    username: lucasbarbosa
    password: lucas123
    driverClassName: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

feign:
  client:
    stock:
      url: http://www.randomnumberapi.com/api/v1.0
    agify:
      url: http://api.agify.io/
    country:
      url: http://restcountries.eu/rest/v2/alpha
    product:
      url: https://random-data-api.com/api/number/random_number
    user:
      url: http://random-data-api.com/api

seller:
  token:
    validity: 60

stock:
  minStock: 1
  maxStock: 10

product:
  minPrice: 1
  maxPrice: 100
